### ISSUE TITLE
Error loading desert_well structure

### ISSUE THREAD

**Issue by diefesson** [FinnSetchell/MoogsSoaringStructures#1]
Minecraft Version: `1.20.1`
NeoForge Version: `47.1.106 (latest)`

<details>
 <summary>Exception stack trace</summary>

~~~~ java
[09:58:10] [Worker-Main-10/ERROR] [minecraft/StructureTemplateManager]: Couldn't load structure mss:desert_well
net.minecraft.ReportedException: Loading NBT data
	at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:480) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:accessories-common.mixins.json:NbtCompoundMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:26) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:474) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:accessories-common.mixins.json:NbtCompoundMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:153) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:99) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.NbtIo.m_128939_(NbtIo.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230377_(StructureTemplateManager.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230372_(StructureTemplateManager.java:217) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:?] {}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230359_(StructureTemplateManager.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mns-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mes-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:APP:mss-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23107!/:?] {}
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_227299_(SinglePoolElement.java:81) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:yungsapi.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:mns-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:mes-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:mss-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_214015_(SinglePoolElement.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:yungsapi.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:mns-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:repurposed_structures-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:mes-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:mss-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
	at com.finndog.mss.world.structures.pieces.PieceLimitedJigsawManager.assembleJigsawStructure(PieceLimitedJigsawManager.java:106) ~[mss-1.1.2-1.20.jar%23237!/:?] {re:classloading}
	at com.finndog.mss.world.structures.GenericJigsawStructure.m_214086_(GenericJigsawStructure.java:213) ~[mss-1.1.2-1.20.jar%23237!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.Structure.m_262864_(Structure.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,xf:fml:forge:structure,re:classloading,xf:fml:forge:structure}
	at net.minecraft.world.level.levelgen.structure.Structure.m_226596_(Structure.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,xf:fml:forge:structure,re:classloading,xf:fml:forge:structure}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223104_(ChunkGenerator.java:513) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_254811_(ChunkGenerator.java:466) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:A}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_255037_(ChunkGenerator.java:448) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_289181_(ChunkStatus.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23107!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
Caused by: java.io.IOException: Invalid tag id: 16
	at net.minecraft.nbt.TagType$1.m_197591_(TagType.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:classloading}
	at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:474) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:accessories-common.mixins.json:NbtCompoundMixin,pl:mixin:A}
	... 45 more
~~~~

</details>

**Comment by VaporeonScripts** [comment]
same
